version: "3.0"
services:
  nginx:
    image: nginx:latest
    container_name: "nginx"
    env_file: ../.env
    ports:
      - 8080:${HLS_PORT}
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../out:/mnt/hls:ro
  minio:
    image: quay.io/minio/minio
    container_name: "minio"
    env_file: ../.env
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASS}
    volumes:
      - ./minio/data:/data
    command: ["server", "/data", "--console-address", ":9001"]
