version: "3.0"
services:
  nginx:
    image: nginx:latest
    container_name: "nginx"
    env_file: ../.env
    ports:
      - 8080:${HLS_PORT}
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../out:/mnt/hls:ro
  minio:
    image: quay.io/minio/minio:latest
    container_name: "minio"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=secret_password
      # - MINIO_ACCESS_KEY=admin
      # - MINIO_SECRET_KEY=secret_password
      # - MINIO_CONFIG_ENV_FILE="/etc/config.env"
    volumes:
      - ./minio/data:/data
      - ./minio/config.env:/etc/config.env:ro
    command: server /data --console-address :9001
